# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='projectimg/'),
        ),
    ]
