# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20170621_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre',
            new_name='name',
        ),
    ]
