# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_auto_20170621_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='nombre',
            new_name='name',
        ),
    ]
