# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_auto_20170621_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='is_destacada',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
