# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_noticia_is_destacada'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCondominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144)),
                ('rut', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=144)),
            ],
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144)),
                ('direccion', models.CharField(max_length=144)),
            ],
        ),
        migrations.CreateModel(
            name='Copropietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144)),
                ('rut', models.CharField(max_length=144)),
                ('documento', models.FileField(blank=True, null=True, upload_to='docs')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.Condominio')),
            ],
        ),
        migrations.AddField(
            model_name='admincondominio',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.Condominio'),
        ),
    ]
