# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_auto_20170627_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincondominio',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admincondominio',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='condominio',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condominio',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
